### ISSUE TITLE
Issue with postgresql recipe

### ISSUE THREAD

**Issue by ghost** [ROGUE-JCTD/rogue-chef-repo#24]
Running into the following when running install shell scripts (with Vagrant set to false) on VMWare VM of Ubuntu 14.04.2 LTS
# Recipe Compile Error in /opt/chef-run/cookbooks/rogue/recipes/postgresql.rb
## NameError

uninitialized constant Chef::Recipe::OpenSSLCookbook
## Cookbook Trace:

  /opt/chef-run/cookbooks/postgresql/recipes/server.rb:20:in `from_file'
  /opt/chef-run/cookbooks/rogue/recipes/postgresql.rb:14:in`from_file'
## Relevant File Content:

/opt/chef-run/cookbooks/postgresql/recipes/server.rb:

 13:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 14:  # See the License for the specific language governing permissions and
 15:  # limitations under the License.
 16:  #
 17:  
 18:  include_recipe "postgresql::ca_certificates"
 19:  
 20>> ::Chef::Recipe.send(:include, OpenSSLCookbook::RandomPassword)
 21:  
 22:  include_recipe "postgresql::client"
 23:  
 24:  # randomly generate postgres password, unless using solo - see README
 25:  if Chef::Config[:solo]
 26:    missing_attrs = %w{
 27:      postgres
 28:    }.select do |attr|
 29:      node['postgresql']['password'][attr].nil?

Running handlers:
[2015-11-30T06:22:14-08:00] ERROR: Running exception handlers
Running handlers complete
[2015-11-30T06:22:14-08:00] ERROR: Exception handlers complete
[2015-11-30T06:22:14-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 4.416708117 seconds
[2015-11-30T06:22:14-08:00] ERROR: uninitialized constant Chef::Recipe::OpenSSLCookbook
[2015-11-30T06:22:15-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by garnertb** [comment]
This was fixed in https://github.com/ROGUE-JCTD/rogue-cookbook/commit/c1f1073f3f50afc1834b577876a1b841b551f550.
