### ISSUE TITLE
rsyslog version 4.0.0 triggers an error when compile cookbook

### ISSUE THREAD

**Issue by charmosz** [ROGUE-JCTD/rogue-chef-repo#25]
Hi,
I try to install and run geoshape in a docker container.
When I start chef client I got an error during the compilation.
Do you have an idea how to prevent that?

`Starting Chef Client, version 11.16.4
[2016-02-23T15:42:04+00:00] INFO: **\* Chef 11.16.4 ***
[2016-02-23T15:42:04+00:00] INFO: Chef-client pid: 2349
[2016-02-23T15:42:38+00:00] INFO: Setting the run_list to ["role[geoshape_core]"] from CLI options
[2016-02-23T15:42:38+00:00] INFO: Run List is [role[geoshape_core]]
[2016-02-23T15:42:38+00:00] INFO: Run List expands to [apt, python, git, rogue::gdal, rogue::postgresql, rogue]
[2016-02-23T15:42:38+00:00] INFO: Starting Chef Run for dbbc828db34d
[2016-02-23T15:42:38+00:00] INFO: Running start handlers
[2016-02-23T15:42:38+00:00] INFO: Start handlers complete.
Compiling Cookbooks...
[2016-02-23T15:42:40+00:00] INFO: ChefHandler light-weight provider already initialized -- overriding!
# 
# Recipe Compile Error in /opt/chef-run/cookbooks/rsyslog/resources/file_input.rb
## ArgumentError

wrong number of arguments (3 for 1)
## Cookbook Trace:

  /opt/chef-run/cookbooks/compat_resource/files/lib/compat_resource.rb:13:in `property'
  /opt/chef-run/cookbooks/rsyslog/resources/file_input.rb:21:in`class_from_file'
## Relevant File Content:

/opt/chef-run/cookbooks/compat_resource/files/lib/compat_resource.rb:

  6:    require 'chef_compat/property'
  7:    require 'chef_compat/mixin/properties'
  8:  
  9:  else
 10:  
 11:    class Chef
 12:      class Resource
 13>>       def self.property(args, &block)
 14:          raise_chef_11_error
 15:        end
 16:  
 17:        def self.resource_name(args, &block)
 18:          raise_chef_11_error
 19:        end
 20:  
 21:        def self.action(args, &block)
 22:          raise_chef_11_error`

**Comment by charmosz** [comment]
I downgrade to rsyslog version 2.2.0 and it works...

**Comment by carrbrpoa** [comment]
Hey @charmosz, how do I do this? I suspect I'm having the same problem here, during install script run.

**Comment by charmosz** [comment]
Hi. You have to change the version in the Berksfile.lock file from 4.0.0 to 2.2.0

**Comment by carrbrpoa** [comment]
I tried it few minutes ago, but when I run the install script again, it seems to pull rogue-chef-repo and overwrite my changes, it backs to 4.0.0. I change `Berksfile.lock`, save it and run `bash geoshape-install.sh` again.

**Comment by charmosz** [comment]
The Berksfile.lock is overwritten at the end of the solo/geoshape-upgrade.sh script which is triggered at the end of the geoshape-install.sh script. If I remember well, I must have done :
- run the geoshape-install.sh script : it will raise the problem
- change the version of rsyslog in the Berksfile.lock file
- manually trigger the few last actions of the geoshape-upgrade.sh :

```
berks vendor /opt/chef-run/cookbooks
cd /opt/chef-run
./geoshape-provision.sh silent
```

**Comment by carrbrpoa** [comment]
It worked @charmosz, thanks! :100:

**Comment by charmosz** [comment]
Great ;)

**Comment by carrbrpoa** [comment]
Did you get another error after? After several minutes of script running, I got this one:

![error](https://cloud.githubusercontent.com/assets/10212618/14675241/6fb8da44-06de-11e6-89a0-41c800e9d5d8.png)

**Comment by charmosz** [comment]
No sorry, I didn't get this error. It seems the error occurred during the installation of the geonode docs. But I guess you can disable this installation. Take a look in the file
`chef-run/cookbooks/rogue/attributes/default.rb`, you could set `default['rogue']['install_docs'] = false`.
Try to rerun `./geoshape-provision.sh` and see!

**Comment by carrbrpoa** [comment]
Thanks @charmosz, I'll try it later and give a feedback for the records ;)

**Comment by carrbrpoa** [comment]
You were right. Adding `install_docs: false` solved. Thanks!

**Comment by charmosz** [comment]
You're welcome!

Le vendredi 22 avril 2016, César Augusto notifications@github.com a
écrit :

> You were right. Adding `install_docs: false' solved. Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/ROGUE-JCTD/rogue-chef-repo/issues/25#issuecomment-213501168

##
