### ISSUE TITLE
keyserver error

### ISSUE THREAD

**Issue by carrbrpoa** [ROGUE-JCTD/rogue-chef-repo#26]
I'm trying to run geoshape-install in a VM hosted by Windows machine, behind a corporate proxy (already configured, I guess, since I could install git with apt-get successfully) and I'm getting the following:

![error_gpg](https://cloud.githubusercontent.com/assets/10212618/14561804/474f6c8c-02ef-11e6-8ce0-9ad0e2a1bbc1.png)

Please note that I replaced the install script line...

`gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3`

...for...

`sudo apt-key adv --keyserver-options http-proxy="http://10.110.115.205:3128" --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D39DC0E3`

...so now at least I don't get a keyserver timed out error, with the original line.

Any ideas?

Thanks in advance

**Comment by wgb** [comment]
Could you post the output of this command with the `--verbose` option flag?

**Comment by carrbrpoa** [comment]
Hey @wgb,

Here it goes, with both commands:

![verbose](https://cloud.githubusercontent.com/assets/10212618/14603884/c26e3836-0546-11e6-997e-1c24c76a0ab1.png)

**Comment by carrbrpoa** [comment]
Progress!
Seems it was a proxy issue, talking to company' infra guys, I was given some workaround.
Thanks anyway.
